### ISSUE TITLE
Example Config file please

### ISSUE THREAD

**Issue by palidin74** [ffddorf/unms-exporter#2]
I have been fighting this for a while and I cant seem to get a config file with the correct context etc. Can you please include an example file. Pretty please

Thank you

**Comment by SaymonDzen** [comment]
I am also interested in this question

**Comment by SaymonDzen** [comment]
Thanks, @m0ppers !
example config.yml
```
token: {YOUR_UNMS_TENANT.unmsapp.com: TOKEN}
```

**Comment by mraerino** [comment]
With https://github.com/ffddorf/unms-exporter/pull/6 i added a proper readme with a lot of docs about configuration. Let me know if something is missing.
