### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by m0ppers** [ffddorf/unms-exporter#21]
I have been told by @mraerino to open an issue :face_with_spiral_eyes: presumably to act as a reminder.

It does not work: https://metrics.kalk.space/d/yFpaB2xGk/network?orgId=1&refresh=10s

I don't have more information unfortunately :face_with_spiral_eyes:

**Comment by mraerino** [comment]
i don't remember what didn't work here, but if it's still an issue i'll fix it if it comes up again
