### ISSUE TITLE
Segfault checking target

### ISSUE THREAD

**Issue by alejandroscf** [ffddorf/unms-exporter#9]
I've been trying to set every thing up, but it didn't work

When requesting http://localhost:9806/?target=unms.example.com I get a segfault in the logs.

Here is how I launch the container and the error It throws (I've redacted the domain and token):

```
# export UNMS_EXPORTER_LOG_LEVEL=debug
# cat /usr/src/unms-exporter/unms_exporter.yml
token: {"unms.example.com": "bla-bla-bla"}
# docker run --name unms_exporter -e UNMS_EXPORTER_LOG_LEVEL \
--volume "/usr/src/unms-exporter/unms_exporter.yml":"/home/unms/unms_exporter.yml" \
--publish 9806:9806 quay.io/ffddorf/unms-exporter \
/usr/local/bin/unms-exporter -c /home/unms/unms_exporter.yml

time="2021-12-25T17:33:03Z" level=info msg="Server starting..." addr="[::]:9806"
time="2021-12-25T17:33:29Z" level=debug msg="Starting request" method=GET url="/?target=unms.example.com"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa1390f]

goroutine 23 [running]:
github.com/ffddorf/unms-exporter/exporter.(*Exporter).collectImpl(0xc000339a00, 0xc000128240, 0x0, 0x0)
	/src/exporter/exporter.go:185 +0x76f
github.com/ffddorf/unms-exporter/exporter.(*Exporter).Collect(0xc000339a00, 0xc000128240)
	/src/exporter/exporter.go:115 +0x6c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:446 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:538 +0xe8e
```

I have no idea why it fails or how to debug it. 
If I query the unms API form the same machine I get the json data without problem.
`curl --include --header "Accept: application/json" --header "x-auth-token: bla-bla-bla" 'https://unms.example.com/nms/api/v2.1/devices?withInterfaces=true'`.

The uisp server version is 1.3.11 and is running in debian 11.2 with Docker version 20.10.12, build e91ed57.

Thanks in advance.
Alejandroscf

**Comment by mraerino** [comment]
i think i have a fix in #10 

can you check out this image tag? `quay.io/ffddorf/unms-exporter:fix-nil-checks`

**Comment by alejandroscf** [comment]
Now I get the error in another line:
```
time="2022-01-04T02:12:31Z" level=info msg="Server starting..." addr="[::]:9806"
time="2022-01-04T02:12:33Z" level=debug msg="Starting request" method=GET url="/?target=unms.example.com"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa14891]

goroutine 27 [running]:
github.com/ffddorf/unms-exporter/exporter.(*Exporter).collectImpl(0xc0002dd9c0, 0xc0004002a0, 0x0, 0x0)
	/src/exporter/exporter.go:164 +0x16f1
github.com/ffddorf/unms-exporter/exporter.(*Exporter).Collect(0xc0002dd9c0, 0xc0004002a0)
	/src/exporter/exporter.go:115 +0x6c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:446 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:538 +0xe8e
```
But I managed to fix it in my [commit](https://github.com/alejandroscf/unms-exporter/commit/89c72ee1363e54f8f2f443bcb8674ae1ea53aecc) I don't know if I can append it to the PR

**Comment by mraerino** [comment]
i pulled in your commit and added some more checks. Wanna check one more time?

**Comment by alejandroscf** [comment]
I've just tried and it's working

**Comment by mraerino** [comment]
i cut release v0.1.1 with the change.

**Comment by alejandroscf** [comment]
I'm sorry but it crashed again after a few days running :/

I think It happened when configuring an antenna before I assigned it to a site. I think the problem is in line [168](https://github.com/ffddorf/unms-exporter/blob/955f4929f5c27f590f75e44528498677cd0c6657/exporter/exporter.go#L168)


The trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa133e3]

goroutine 43356 [running]:
github.com/ffddorf/unms-exporter/exporter.(*Exporter).collectImpl(0xc0002afa00, 0xc0002aa180, 0x0, 0x0)
        /src/exporter/exporter.go:168 +0x243
github.com/ffddorf/unms-exporter/exporter.(*Exporter).Collect(0xc0002afa00, 0xc0002aa180)
        /src/exporter/exporter.go:115 +0x6c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        /go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:446 +0x1a2
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        /go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:538 +0xe8e
```

**Comment by mraerino** [comment]
thanks for reporting. will look at a fix soon

**Comment by mraerino** [comment]
Fix in https://github.com/ffddorf/unms-exporter/pull/11
Image is `quay.io/ffddorf/unms-exporter:fix-nil-checks-round-2`

**Comment by mraerino** [comment]
would you be willing to share a redacted json of the devices api response from your instance? i feel like it might be useful for regression testing.

**Comment by alejandroscf** [comment]
Looks like it works, but I couldn't check this edge case right now.

**Comment by alejandroscf** [comment]
I've just had to install new antennas and it worked nicely they where assigned to the "no-site" location tag until I assigned them to a site, so it looks solved.

About the json file, I'm sorry I have a list of fields to redact, but I haven't had the time to process the json.
